#!/bin/sh

workspace_dir=$1
output_dir=$2

curl http://pyyaml.org/download/libyaml/yaml-$VERSION.tar.gz -s
tar zxf yaml-$VERSION.tar.gz

cd yaml-$VERSION
env CFLAGS=-fPIC ./configure --enable-static --disable-shared --prefix=$output_dir
make
make install