#!/bin/sh

workspace_dir=$1
output_dir=$2

curl -O http://archive.ubuntu.com/ubuntu/pool/main/x/xorg-server/xorg-server_1.7.6.orig.tar.gz -s -o - | tar zxf

cd xorg-server-1.7.6
env CFLAGS=-fPIC ./configure --enable-static --disable-shared --prefix=$output_dir
make
make install